language: python
python:
  - "2.6"
  - "2.7"

install:
  - pip install coveralls
  # make sure we have the latest version
  - pip install -U nose
  - pip install git+https://github.com/Byron/bcore.git
  - pip install git+https://github.com/shotgunsoftware/python-api.git
  - pip install git+https://github.com/Byron/tk-core
  # prepare fixture, which has to be downloaded manually
  - src/python/btank/tests/fixtures/setup_fixtures
script:
  - 'cd src/python/btank/tests && nosetests --with-coverage . utility/patch/test_patch.py'
after_success:
  - coveralls
